name: GeneralCommandsRevene
version: '${project.version}'
main: revene.generalcommands.GeneralCommandsMain
api-version: 1.18
commands:
  nerd:
    description: nerd
    usage: /<command>
    aliases: nerdo
  nou:
    description: NO YOU
    usage: /<command>
    aliases: noyou
  technoblade:
    description: fly high
    usage: /<command>
  rickroll:
    description: Rickrolls you lol
    usage: /<command>
    aliases: rickastley
  forum:
    description: Forums Link
    usage: /<command>
    aliases: forums
  pong:
    description: Ping
    usage: /<command>
  store:
    description: Store link
    usage: /<command>
  discord:
    description: Discord Link
    usage: /<command>
  pingreload:
    description: Reloads the plugin.
  ping:
    description: The main command for SpigotPing.
  bye:
    description: Kicks You
    usage: /<command>
    aliases: goodbye
  hello:
    description: Hello
    usage: /<command>
    aliases: hi

