name: GeneralCommandsRevene
version: '1.1-SNAPSHOT'
main: revene.generalcommands.HelloAndProMode
api-version: 1.18
commands:
  store:
    description: Store link
    usage: /<command>
  discord:
    description: Discord Link
    usage: /<command>
  pingreload:
    description: Reloads the plugin.
  ping:
    description: The main command for SpigotPing.
  bye:
    description: Kicks You
    usage: /<command>
  hello:
    description: Hello
    usage: /<command>
    aliases: hi

